### ISSUE TITLE
 Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by Xeyk** [diva-exchange/i2p#1]
I ran this in docker using your beginner instructions and unfortunately it errors out. Have you seen this before? 

`darkhttpd/1.12, copyright (c) 2003-2016 Emil Mikulic.

listening on: http://0.0.0.0:8080/

[14:50:29.608126] STUBBY: Stubby version: Stubby 0.3.0

[14:50:29.610035] STUBBY: Read config from file /home/i2pd/network/stubby.yml

[14:50:29.610171] STUBBY: DNSSEC Validation is OFF

[14:50:29.610177] STUBBY: Transport list is:

[14:50:29.610180] STUBBY:   - TLS

[14:50:29.610184] STUBBY: Privacy Usage Profile is Strict (Authentication required)

[14:50:29.610187] STUBBY: (NOTE a Strict Profile only applies when TLS is the ONLY transport!!)

[14:50:29.610190] STUBBY: Starting DAEMON....

Oct 18 14:50:29.611 [notice] Tor 0.4.3.5 running on Linux with Libevent 2.1.11-stable, OpenSSL 1.1.1g, Zlib 1.2.11, Liblzma 5.2.5, and Libzstd 1.4.5.

Oct 18 14:50:29.611 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning

Oct 18 14:50:29.611 [warn] Tor was compiled with zstd 1.4.4, but is running with zstd 1.4.5. For safety, we'll avoid using advanced zstd functionality.

Oct 18 14:50:29.611 [notice] Read configuration file "/home/i2pd/network/torrc".

Oct 18 14:50:29.614 [notice] Wow!  I detected that you have 24 CPUs. I will not autodetect any more than 16, though.  If you want to configure more, set NumCPUs in your torrc

Oct 18 14:50:29.614 [warn] You specified a public address '0.0.0.0:9050' for SocksPort. Other people on the Internet might find your computer and use it as an open proxy. Please don't allow this unless you have a good reason.

Oct 18 14:50:29.614 [notice] Opening Socks listener on 0.0.0.0:9050

Oct 18 14:50:29.614 [notice] Opened Socks listener on 0.0.0.0:9050

Illegal instruction (core dumped)
`

**Comment by diva-exchange** [comment]
Thank you for your report. Not seen this before. It looks to me as "tor" produces the illegal instruction. Two questions: 

1. Does our other Docker Image (I2P without Tor), tagged as "latest", work for you?
2. Any chance that you post the core dump here or on https://codeberg.org/diva.exchange/i2p ?

Docker Image, tagged as "latest": https://hub.docker.com/layers/divax/i2p/latest/images/sha256-dd51048720f5485a784abe1fa21d9d7c054c87b218829d1aec477143ef8153f9?context=explore

**Comment by Xeyk** [comment]
Sorry about the delayed reply. The I2p version posts the exact same error.

I'll work on getting you the core dump today. Just to be sure I'm getting you the right thing, do these instructions look correct? 

https://dev.to/mizutani/how-to-get-core-file-of-segmentation-fault-process-in-docker-22ii

**Comment by diva-exchange** [comment]
The instructions given https://dev.to/mizutani/how-to-get-core-file-of-segmentation-fault-process-in-docker-22ii will be challenging, since it requires you to rebuild the docker image on your infrastructure. This might be cumbersome for you.

Now, since you have the same problem with i2p:latest, it is not Tor. Two possibilities: a) i2pd itself (which is the I2P binary) and Stubby (which is providing private DNS lookups).

1.
Before we run after the core dump file - what's the output of "uname -a" on your infrastructure where you want to run the docker image i2p:latest?
2.
Are you able to get the code to your infrastructure, like "git clone -b master https://codeberg.org/diva.exchange/i2p.git && cd i2p" and then build it locally: "sudo ./bin/build.sh" ?

**Comment by Xeyk** [comment]
4.4.0-190-generic #220-Ubuntu SMP Fri Aug 28 23:02:15 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

I was able to successfully built it locally. This time, the message is a little different and certainly points to Stubby as the issue.

`[17:34:09.988349] STUBBY: Stubby version: Stubby 0.3.0


[17:34:09.990354] STUBBY: Read config from file /home/i2pd/network/stubby.yml


[17:34:09.990568] STUBBY: DNSSEC Validation is OFF


[17:34:09.990577] STUBBY: Transport list is:


[17:34:09.990580] STUBBY:   - TLS


[17:34:09.990583] STUBBY: Privacy Usage Profile is Strict (Authentication required)


[17:34:09.990587] STUBBY: (NOTE a Strict Profile only applies when TLS is the ONLY transport!!)


[17:34:09.990590] STUBBY: Starting DAEMON....


Illegal instruction (core dumped)`

**Comment by diva-exchange** [comment]
Thank you! I2Pd was just now released as 2.34.0 so we just rebuilt the Docker Images and released it. However, if stubby is the reason for the "illegal instruction" this new release won't help. Right now the images are rebuilding on https://hub.docker.com/r/divax/i2p and they will be available today in latest about 1 hour.

Solution approach: we will produce a docker image without stubby (so: I2Pd only) and we will release the image in the next 48 hours. Maybe you will find some time to test it on your systems. That would be much appreciated.

**Comment by Xeyk** [comment]
I will certainly test that out. Would it be possible to get a version with tor+i2p included without stubby? 

Just an FYI as well - I tried building an earlier release of your i2p+tor version, and it gave the same error message on my system.

**Comment by diva-exchange** [comment]
OK, stubby removed - docker image available: 
1. docker pull divax/i2p:i2p-tor
2. Something like (adapted to your needs) to start the container: docker run --env PORT_TOR=9950 --env PORT_HTTP_PROXY=4544 -p 7170:7070 -p 4544:4444 -p 9950:9050 -p 8080:8080 -d --name i2p-tor divax/i2p:i2p-tor

Hope it works!

We tested the docker images on:
* Linux 4.13.0-43-generic #48~16.04.1-Ubuntu SMP Thu May 17 12:56:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Linux 4.15.0-121-generic #123-Ubuntu SMP Mon Oct 5 16:16:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Linux 5.4.0-51-generic #56-Ubuntu SMP Mon Oct 5 14:28:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Xeyk** [comment]
It's working like a charm. Stubby was definitely the issue. Thank you for all your hard work!
