### ISSUE TITLE
[BUG] Document web console port

### ISSUE THREAD

**Issue by mtalexan** [diva-exchange/i2p#8]
The port for accessing the configuration webconsole appears to be port `7070` according to the hardcoded `i2pd.org.conf`.  This isn't documented anywhere in the README.md.

**Comment by diva-exchange** [comment]
Great stuff: please create a PR.

**Comment by mtalexan** [comment]
You beat me to it. I was going to create a PR and address all my reports once they were confirmed how they should be solved.
