### ISSUE TITLE
How to set up reseed proxy?

### ISSUE THREAD

**Issue by myrshfrs** [diva-exchange/i2p#9]
It seems that Reseed's websites are all blocked in my country. The log says " Reseed: SU3 download failed" and I can't access the webconsole.

**Comment by diva-exchange** [comment]
First, please try using tor to download the su3 (assuming your using i2p-tor), here, https://github.com/diva-exchange/i2p?tab=readme-ov-file#get-started like this:

```
$ docker pull divax/i2p:current-i2p-tor
$ docker run --env PORT_TOR=9950 --env PORT_HTTP_PROXY=4544 --env ENABLE_HTTPPROXY=1 -p 7170:7070 -p 4544:4444 -p 9950:9050 -p 8080:8080 -d --name i2p-tor divax/i2p:current-i2p-tor
```

Assuming that the docker container is running properly, do download the su3 file (you can use any reseed server, here is reseed.diva.exchange as an example:
```
$ curl --output test.su3 -x socks://127.0.0.1:9950 https://reseed.diva.exchange/i2pseeds.su3
```

RESULT:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 76374  100 76374    0     0   2142      0  0:00:35  0:00:35 --:--:-- 17703

```

Please give feedback if this works as expected from whereever you are.

**Comment by myrshfrs** [comment]
curl: (97) Can't complete SOCKS4 connection to 0.0.0.0:0. (91), request rejected or failed.

**Comment by diva-exchange** [comment]
Please show your docker setup, like this:
`$ docker ps -a | grep divax`

and also your complete curl command (the divax tor proxy is listening on localhost, 127.0.0.1, and on port 9950, by default).

**Comment by myrshfrs** [comment]
![无标题](https://github.com/diva-exchange/i2p/assets/6205312/b81a4fd7-277e-45d3-956d-1a215be223c0)

**Comment by diva-exchange** [comment]
docker environment looks OK. BUT: it looks like the tor proxy is not propely working within the container. Could you please show the logs of the i2p-tor container, like this: 

`docker logs i2p-tor | more`

Here is an example how the output of the container log should look like:

```
Jan 21 16:42:23.704 [notice] Tor 0.4.7.16 running on Linux with Libevent 2.1.12-
stable, OpenSSL 1.1.1w, Zlib 1.2.12, Liblzma 5.2.5, Libzstd 1.5.2 and Unknown N/
A as libc.
Jan 21 16:42:23.704 [notice] Tor can't help you if you use it wrong! Learn how t
o be safe at https://support.torproject.org/faq/staying-anonymous/
Jan 21 16:42:23.704 [notice] Read configuration file "/home/i2pd/network/torrc".
Jan 21 16:42:23.705 [warn] You specified a public address '0.0.0.0:9050' for Soc
ksPort. Other people on the Internet might find your computer and use it as an o
pen proxy. Please don't allow this unless you have a good reason.
Jan 21 16:42:23.705 [notice] Opening Socks listener on 0.0.0.0:9050
Jan 21 16:42:23.705 [notice] Opened Socks listener connection (ready) on 0.0.0.0
:9050
Jan 21 16:42:23.706 [warn] Fixing permissions on directory /var/lib/tor
[21/Jan/2024:16:42:23 +0000]@579/info - Log: Logging level set to info
[21/Jan/2024:16:42:23 +0000]@579/none - i2pd v2.50.2 (0.9.61) starting.
..
[21/Jan/2024:16:42:23 +0000]@579/info - AESNI enabled
[21/Jan/2024:16:42:23 +0000]@579/info - Daemon: Bandwidth set to 48KBps
[21/Jan/2024:16:42:23 +0000]@579/info - Daemon: Using system limit in 1
048576 max open files
[...]
```

**Comment by diva-exchange** [comment]
solved.
